# Generated by Django 3.1.7 on 2021-03-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210304_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
